services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
      - "4243:4243"
    volumes:
      - ../:/usr/src/app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
